/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

namespace main.android.demo.opentoksamples
{

	public sealed class R
	{
		public sealed class attr
		{
		}

		public sealed class color
		{
			public const int black_grey = 0x7f040000;
			public const int blue = 0x7f040001;
			public const int color0_gradient = 0x7f040002;
			public const int color1_gradient = 0x7f040003;
			public const int dark_grey = 0x7f040004;
			public const int grey = 0x7f040005;
			public const int init_gradient = 0x7f040006;
			public const int trans = 0x7f040007;
			public const int trans_dark_grey = 0x7f040008;
			public const int trans_white = 0x7f040009;
			public const int white = 0x7f04000a;
		}

		public sealed class drawable
		{
			public const int archiving_off = 0x7f020000;
			public const int archiving_on = 0x7f020001;
			public const int audio_only = 0x7f020002;
			public const int avatar = 0x7f020003;
			public const int button_background = 0x7f020004;
			public const int camera = 0x7f020005;
			public const int headset = 0x7f020006;
			public const int high_congestion = 0x7f020007;
			public const int ic_launcher = 0x7f020008;
			public const int mid_congestion = 0x7f020009;
			public const int mute_pub = 0x7f02000a;
			public const int mute_sub = 0x7f02000b;
			public const int no_video = 0x7f02000c;
			public const int publisher = 0x7f02000d;
			public const int silhouette2 = 0x7f02000e;
			public const int speaker_active = 0x7f02000f;
			public const int unmute_pub = 0x7f020010;
			public const int unmute_sub = 0x7f020011;
		}

		public sealed class id
		{
			public const int archiving = 0x7f080006;
			public const int archivingbar = 0x7f08002d;
			public const int archivingimg = 0x7f08002e;
			public const int archivingstatus = 0x7f08002f;
			public const int audioOnlyView = 0x7f080016;
			public const int avatar = 0x7f080018;
			public const int bottomcontainer = 0x7f080028;
			public const int congestionIndicator = 0x7f080012;
			public const int connectionStatus = 0x7f080009;
			public const int divider = 0x7f080030;
			public const int divider1 = 0x7f080031;
			public const int divider2 = 0x7f08002a;
			public const int endCall = 0x7f080004;
			public const int fragment_pub_container = 0x7f08001b;
			public const int fragment_pub_status_container = 0x7f08001c;
			public const int fragment_sub_container = 0x7f08001a;
			public const int fragment_sub_quality_container = 0x7f08001d;
			public const int layoutPubFragment = 0x7f080000;
			public const int layoutSubFragment = 0x7f08000a;
			public const int layoutSubQualityFragment = 0x7f080010;
			public const int line1 = 0x7f080008;
			public const int line2 = 0x7f08000e;
			public const int listview = 0x7f08001e;
			public const int loadingSpinner = 0x7f080015;
			public const int mainlayout = 0x7f080013;
			public const int menu_settings = 0x7f080035;
			public const int message = 0x7f080026;
			public const int messageView = 0x7f080024;
			public const int messagebox = 0x7f080023;
			public const int mutePublisher = 0x7f080002;
			public const int muteSubscriber = 0x7f08000c;
			public const int pager = 0x7f080021;
			public const int preview = 0x7f080025;
			public const int publisherStatusWidget = 0x7f080005;
			public const int publisherView = 0x7f080019;
			public const int publisherWidget = 0x7f080001;
			public const int publishermeter = 0x7f08002c;
			public const int publishername = 0x7f08002b;
			public const int publisherpicture = 0x7f080029;
			public const int publisherview = 0x7f080020;
			public const int scroller = 0x7f080022;
			public const int sendMessageButton = 0x7f080027;
			public const int statusLabel = 0x7f080007;
			public const int subscriberAudioLevelWidget = 0x7f08000b;
			public const int subscriberName = 0x7f08000d;
			public const int subscriberStatusWidget = 0x7f080011;
			public const int subscriberView = 0x7f080014;
			public const int subscriberWidget = 0x7f08000f;
			public const int subscribermeter = 0x7f080017;
			public const int subscribername = 0x7f080033;
			public const int subscriberpicture = 0x7f080032;
			public const int subscriberview = 0x7f08001f;
			public const int swapCamera = 0x7f080003;
			public const int volume = 0x7f080034;
		}

		public sealed class layout
		{
			public const int layout_fragment_pub_control = 0x7f030000;
			public const int layout_fragment_pub_status = 0x7f030001;
			public const int layout_fragment_sub_audio_level = 0x7f030002;
			public const int layout_fragment_sub_control = 0x7f030003;
			public const int layout_fragment_sub_quality = 0x7f030004;
			public const int layout_ui_activity = 0x7f030005;
			public const int main_activity = 0x7f030006;
			public const int main_layout = 0x7f030007;
			public const int room = 0x7f030008;
			public const int voice_only_layout = 0x7f030009;
			public const int voice_row = 0x7f03000a;
		}

		public sealed class menu
		{
			public const int activity_main = 0x7f070000;
		}

		public sealed class @string
		{
			public const int app_name = 0x7f050000;
			public const int archivingOff = 0x7f050001;
			public const int archivingOn = 0x7f050002;
			public const int audioOnly = 0x7f050003;
			public const int audiodevice = 0x7f050004;
			public const int clearNotificationService = 0x7f050005;
			public const int endCall1 = 0x7f050006;
			public const int endCall2 = 0x7f050007;
			public const int helloworld = 0x7f050008;
			public const int helloworldcapturer = 0x7f050009;
			public const int helloworldemulator = 0x7f05000a;
			public const int helloworldrenderer = 0x7f05000b;
			public const int helloworldsubclassing = 0x7f05000c;
			public const int helloworldui = 0x7f05000d;
			public const int menu_settings = 0x7f05000e;
			public const int notification = 0x7f05000f;
			public const int send = 0x7f050010;
			public const int swapStr = 0x7f050011;
			public const int voinceonly = 0x7f050012;
		}

		public sealed class style
		{
			/// <summary>
			/// Theme customizations available in newer API levels can go in
			/// res/values-vXX/styles.xml, while customizations related to
			/// backward-compatibility can go here.
			/// <p/>
			/// API 11 theme customizations can go here.
			/// API 14 theme customizations can go here.
			/// </summary>
			public const int AppBaseTheme = 0x7f060000;
			/// <summary>
			/// All customizations that are NOT specific to a particular API-level can go here.
			/// </summary>
			public const int AppTheme = 0x7f060001;
		}
	}

}